version: "3.6"

services:
  arango:
    image: arangodb
    ports:
      - 8529:8529
    volumes:
      - arango_data:/var/lib/arangodb3
    environment:
      ARANGO_ROOT_PASSWORD: password

volumes:
  arango_data:
